// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `OrmLiteConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Andrii\Source\Repos\OrmLite\OrmLite\App_Data\OrmLiteDatabase.mdf;Integrated Security=true`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments

#pragma warning disable 1591

using ServiceStack.DataAnnotations;
using ServiceStack.Model;

namespace OrmLiteConnection
{
	[Alias("User")]
	public class User : IHasId<int>
	{
		[Required]
		public string FirstName { get; set; }

		[Required]
		public string LastName { get; set; }

		[Alias("Id")]
		[AutoIncrement]
		public int Id { get; set; }
	}
}

#pragma warning restore 1591